### PR TITLE
docs: matching readme to lock files

### LINKED ISSUE #135: Update demos README to match lock file
If the project includes a `yarn.lock` file, ask to use `yarn`
If it contains a `package-lock.json`, use `npm`

### PR DESCRIPTION
**Pull request by MoskalykA**
# Pull Request

## Related issue
Fixes #135 

## What does this PR do?
- Matches readme to lock files

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by bidoubiwa — CHANGES_REQUESTED** [review]
Hey @MoskalykA ! Thanks a lot for your contribution :) 🔥

Here is my review 

- For `/ecommerce` the changes made on the commands are good, but the `requirements` section should require yarn also.
- In `/nobel-prize` in the readme line 81, you can remove the `npm` mention
- Can you remove the `yarn.lock` from `/tenant-token/seed` ? (this one is a bonus haha)

**Comment by MoskalykA** [comment]
It's OK

**Review by bidoubiwa — APPROVED** [review]
LGTM 🔥

**Comment by ferdi05** [comment]
Hello @MoskalykA. Thank you for contributing to Meilisearch! If you are participating in [Hacktoberfest](https://blog.meilisearch.com/contribute-hacktoberfest-2022/), and you would like to receive some swag from Meilisearch too, please complete [this form](https://meilisearch.typeform.com/to/idt5qugY).

**Pull request merged**
