### PR TITLE
Update Meilisearch wording in the README.md

### LINKED ISSUE #35: Use of Meilisearch instead of MeiliSearch in the README
Currently, the README has MeiliSearch. We need to change it to Meilisearch.

### PR DESCRIPTION
**Pull request by nicolasvienot**
# Pull Request

## What does this PR do?
Fixes #35

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

⚠️ This is also a test for the Vercel integration (rights needed for the tenant-token demo when creating a PR)

### CODE REVIEW

**Comment by ferdi05** [comment]
Thanks @nicolasvienot !!

@shivaylamba looks like there's still an issue with the tenant token demo

**Comment by nicolasvienot** [comment]
Hey @ferdi05,
I investigated for #43 and left a comment there, I think this should fix your problems with the `Vercel – demo-tenant-token` GitHub check 😄

**Comment by CaroFG** [comment]
Any updates?

**Comment by ferdi05** [comment]
cc @shivaylamba I didn't check the results of the test

**Comment by shivaylamba** [comment]
Hi so I have made all the relevant changes as suggested by @nicolasvienot so ideally this should work fine now.

**Pull request merged**
